---
title: "epi261"
author: "Aditi Goyal"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
library(epitools)
library(abind)
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
make_table=function(dats, nrow, ncol, col_names=NULL, row_names=NULL){
  data = matrix(dats, nrow=nrow, ncol=ncol, byrow=TRUE)
  table = as.table(data)
  rowsum=rowSums(table)
  cbind(table, rowsum)
  print(table)
  
#   print(rowSums(table))
#   
#   df$TOTALS <- rowSums(df)
# Create a new data frame containing the column sums for the data frame */
# 
# dfTot <- colSums(df)
# 
# Append the column sums data frame to the data frame of numeric values *.
#df <- rbind(df, dfTot)
  colnames(table) = col_names
  rownames(table) = row_names
  print(table)
  return(table)
}
```

```

chisquared=function(t){
  return(chisq.test(t))
}

fisher_exact=function(t){
  return(fisher.test(t))
}

crude_odd_ratio=function(t){
  return(oddsratio(t))
}

crude_risk_ratio=function(t){
  return(riskratio(t, rev="both"))
}

mcnemars_test=function(t){
  return(mcnemar.test(t))
}

breslowday.test = function(x, OR=NA, printORi.s=TRUE){
  ## function to compute the Breslow Day test of homogeneity for a 2 by 2 by k table
  ## x is a three dim array, 2x2xk
  ## tests to see if all strata have the same OR
  ## if OR is not given, the Mantel-Haenszel estimate is used.
  if(is.na(OR)) {
    OR = mantelhaen.test(x)$estimate
    names(OR) = ""
  } 
  OR.i <- apply(x, 3,  function(x) x[1,1] * x[2,2] / x[1,2] /x[2,1])
  k = dim(x)[3]
  n11k = x[1,1,]
  n21k = x[2,1,]
  n12k = x[1,2,]
  n22k = x[2,2,]
  row1sums = n11k + n12k
  row2sums = n21k + n22k
  col1sums = n11k + n21k
  Amax = apply(cbind(row1sums,col1sums),1,min)
  ## Astar must be no more than col1sums and no more than row1sums
  bb = row2sums +row1sums * OR - col1sums*(1-OR)
  determ = sqrt(bb^2 + 4 * (1-OR) *  OR * row1sums * col1sums)
  Astar = (-bb + cbind( -determ, determ))/ (2 -2*OR)
  Astar = ifelse(Astar[,1] <= Amax & Astar[,1] >= 0, Astar[,1], Astar[,2])
  ## print(Astar)
  Bstar = row1sums - Astar
  Cstar = col1sums - Astar
  Dstar = row2sums - col1sums + Astar
  Var = apply(1 / (.5+cbind(Astar,Bstar,Cstar,Dstar)), 1, sum)^(-1)
  ## print(Var)
  X2 = sum( (x[1,1,] - Astar)^2/Var )
  pvalue = 1 - pchisq(X2,k-1)
  if(printORi.s) {
    out <- rbind(log(OR.i), 1/Var)
    dimnames(out)[[1]] <- c("log OR","Weight")
    print(out)
  }
  return(unlist(list(OR = OR, Stat = X2, df = k-1, pvalue = pvalue)))
}

```

```{r}
d=c(112,79,102,116)
c=c("Died", "Survived")
r=c("NotOxygen", "Oxygen")
t=make_table(d, 2, 2, c, r)
```

```{r}
chisq.test(t)
```

```{r}
fisher.test(t)
```

```{r}
oddsratio(t)
```

```{r}
riskratio(t, rev="both")
```

```{r}
mcnemar.test(t)
```

```{r}
table1 = matrix(c(1,1,0,0), nrow=2, ncol=2, byrow=TRUE)
table2 = matrix(c(0,1,1,0), nrow=2, ncol=2, byrow=TRUE)
table3 = matrix(c(1,0,0,1), nrow=2, ncol=2, byrow=TRUE)
table4 = matrix(c(0,0,1,1), nrow=2, ncol=2, byrow=TRUE)
data = abind(
replicate(9, table1),
replicate(16, table2),
replicate(37, table3),
replicate(82, table4),
along=3)

mantelhaen.test(data)
```

```{r}

table=make_table(c(112, 79, 102, 116), 2, 2, col_names = c("yes smoker", "no smoker"), row_names = c('hip fracture', 'control'))
```

```{r}
chisq.test(table)
```
```{r}
fisher.test(table)
```
```{r}
oddsratio(table)
```

```{r}
low=make_table(c(77, 39, 28, 16), 2, 2, col_names = c("yes smoker", "no smoker"), row_names = c('hip fracture', 'control'))
med=make_table(c(21, 24, 34, 46), 2, 2, col_names = c("yes smoker", "no smoker"), row_names = c('hip fracture', 'control'))
high=make_table(c(14, 16, 40, 54),2, 2, col_names = c("yes smoker", "no smoker"), row_names = c('hip fracture', 'control'))
all=abind(low, med, high, along = 3)
mantelhaen.test(all)
```
```{r}
breslowday.test = function(x, OR=NA, printORi.s=TRUE){
  ## function to compute the Breslow Day test of homogeneity for a 2 by 2 by k table
  ## x is a three dim array, 2x2xk
  ## tests to see if all strata have the same OR
  ## if OR is not given, the Mantel-Haenszel estimate is used.
  if(is.na(OR)) {
    OR = mantelhaen.test(x)$estimate
    names(OR) = ""
  } 
  OR.i <- apply(x, 3,  function(x) x[1,1] * x[2,2] / x[1,2] /x[2,1])
  k = dim(x)[3]
  n11k = x[1,1,]
  n21k = x[2,1,]
  n12k = x[1,2,]
  n22k = x[2,2,]
  row1sums = n11k + n12k
  row2sums = n21k + n22k
  col1sums = n11k + n21k
  Amax = apply(cbind(row1sums,col1sums),1,min)
  ## Astar must be no more than col1sums and no more than row1sums
  bb = row2sums +row1sums * OR - col1sums*(1-OR)
  determ = sqrt(bb^2 + 4 * (1-OR) *  OR * row1sums * col1sums)
  Astar = (-bb + cbind( -determ, determ))/ (2 -2*OR)
  Astar = ifelse(Astar[,1] <= Amax & Astar[,1] >= 0, Astar[,1], Astar[,2])
  ## print(Astar)
  Bstar = row1sums - Astar
  Cstar = col1sums - Astar
  Dstar = row2sums - col1sums + Astar
  Var = apply(1 / (.5+cbind(Astar,Bstar,Cstar,Dstar)), 1, sum)^(-1)
  ## print(Var)
  X2 = sum( (x[1,1,] - Astar)^2/Var )
  pvalue = 1 - pchisq(X2,k-1)
  if(printORi.s) {
    out <- rbind(log(OR.i), 1/Var)
    dimnames(out)[[1]] <- c("log OR","Weight")
    print(out)
  }
  return(unlist(list(OR = OR, Stat = X2, df = k-1, pvalue = pvalue)))
}
```



```{r}
apply(all, 3, oddsratio)
```
```{r}
breslowday.test(all)
```


```{r}
table1 = matrix(c(1,1,0,0), nrow=2, ncol=2, byrow=TRUE)
table2 = matrix(c(0,1,1,0), nrow=2, ncol=2, byrow=TRUE)
table3 = matrix(c(1,0,0,1), nrow=2, ncol=2, byrow=TRUE)
table4 = matrix(c(0,0,1,1), nrow=2, ncol=2, byrow=TRUE)
data = abind(
replicate(9, table1),
replicate(16, table2),
replicate(37, table3),
replicate(82, table4),
along=3)


mantelhaen.test(data)
```

